web/artproject/artproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accountapp/', include('accountapp.urls')),
    path('subapp/', include('subapp.urls')),
    path('secondapp/', include('secondapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #url/media/파일명 점근을 가능하게 한다.

web/artproject/mainapp/urls.py
from django.urls import path 
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = 'mainapp'
urlpatterns = [
    path('', views.home, name='home'), 
    path('map/', views.map, name='map'), #postlist보여줌
    path('<int:pk>/',views.posting, name="posting"), #post 세부내용
    path('upload/', views.upload, name='upload'), #postupload 
    path('<int:pk>/remove/', views.remove_post, name='remove_post'),
    path('map/<int:num>/', views.RegionPostList, name='RegionPostList'),
    path('edit_posting', views.edit_posting, name='edit_posting'),
]

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/artproject/secondapp/urls.py
from django.urls import path 
from . import views

app_name = 'secondapp'
urlpatterns = [
    path("place_search/", views.place_search, name="place_search"),
    path('place_deatil/<int:pk>', views.place_detail, name="place_detail"),
]

web/artproject/subapp/urls.py
from django.urls import path 
from . import views

app_name = 'subapp'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('detail/<int:content_pk>', views.detail, name='detail'),
]

web/artproject/mainapp/models.py
from django.db import models
import os
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    name=models.CharField(max_length=50)
    item=models.CharField(max_length=50) # 카테고리 
    rating= models.IntegerField()
    date=models.DateField(null=True, blank=True)
    image=models.ImageField(upload_to='userimg', null=True)
    comment=models.TextField()
    country = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return f'{self.pk} : {self.name}'

    def delete(self, *args, **kwargs):
        super(Post, self).delete(*args, **kwargs)
        if self.image : 
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.path))

web/artproject/mainapp/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm): 
    class Meta:
        model = Post
        fields = ('name', 'item','rating','date','image','comment','country','city')

web/artproject/mainapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import Post
from .forms import PostForm
from django.db.models import Q
# Create your views here.

def home(request):
    return render(request, 'mainapp/home.html')

@login_required(login_url='/accountapp/login')
def map(request):
    context={}
    postlist = Post.objects.filter(user = request.user)
    imageitem = postlist.exclude(image = '')
    # print(imageitem)
    # if postlist:
    Seoul = imageitem.filter(country = '서울').order_by('-date').first()
    Busan = imageitem.filter(country = '부산').order_by('-date').first()
    Gwangju = imageitem.filter(country = '광주').order_by('-date').first()
    Ulsan = imageitem.filter(country = '울산').order_by('-date').first()
    Daegu = imageitem.filter(country = '대구').order_by('-date').first()
    Daejeon = imageitem.filter(country = '대전').order_by('-date').first()
    Incheon = imageitem.filter(country = '인천').order_by('-date').first()

    GG = imageitem.filter(country = '경기도').order_by('-date').first()
    GW = imageitem.filter(country = '강원도').order_by('-date').first()
    CN = imageitem.filter(Q(country = '충청남도')|Q(country='세종시')).order_by('-date').first()
    CB = imageitem.filter(country = '충청북도').order_by('-date').first()
    GB = imageitem.filter(country = '경상북도').order_by('-date').first()
    JB = imageitem.filter(country = '전라북도').order_by('-date').first()
    GN = imageitem.filter(country = '경상남도').order_by('-date').first()
    JN = imageitem.filter(country = '전라남도').order_by('-date').first()
    Jeju = imageitem.filter(country = '제주도').order_by('-date').first()
    
    context['list'] = {'Seoul':Seoul, 'Busan':Busan, 'Gwangju':Gwangju, 'Ulsan':Ulsan, 'Daegu':Daegu, 'Daejeon':Daejeon, 'Incheon':Incheon,
                        'GG':GG, 'GW':GW, 'CN':CN, 'CB':CB, 'GB':GB, 'JB':JB, 'GN':GN, 'JN':JN, 'Jeju':Jeju}
    context['postlist'] = postlist # real 게시물 전체 복록
    print(context['list'])
    return render(request, 'mainapp/map.html', context)

def posting(request, pk):
    # 게시글(Post) 중 pk(primary_key)를 이용해 하나의 게시글(post)를 검색
    post = Post.objects.get(pk=pk)
    # posting.html 페이지를 열 때, 찾아낸 게시글(post)을 post라는 이름으로 가져옴
    return render(request, 'mainapp/posting.html', {'post':post})

@login_required(login_url='/accountapp/login')
def upload(request):
    if request.method == 'POST':
        if 'image' in request.FILES:
            new_article=Post.objects.create(
                user = request.user,
                name=request.POST['name'],
                comment=request.POST['comment'],
                image=request.FILES['image'],
                rating=request.POST['rating'],
                # item=request.POST['item'],
                item = "전시회",
                date=request.POST['date'],
                country=request.POST['country'],
                city=request.POST['city'],
            )
        else:
            new_article=Post.objects.create(
                user = request.user,
                name=request.POST['name'],
                comment=request.POST['comment'],
                rating=request.POST['rating'],
                # item=request.POST['item'],
                item = "전시회",
                date=request.POST['date'],
                country=request.POST['country'],
                city=request.POST['city'],
            )
        return redirect('mainapp:map')
    return render(request, 'mainapp/upload.html')

@login_required(login_url='/accountapp/login')
def remove_post(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('mainapp:map')
    return render(request, 'mainapp/remove_post.html', {'Post': post})

@login_required(login_url='/accountapp/login')
def RegionPostList(request, num):
    postlist = Post.objects.filter(user = request.user)
    context={}
    if num == 1:
        postlist = postlist.filter(country = '서울').order_by('-date')
        region = '서울'
    elif num == 2:
        postlist = postlist.filter(country = '부산').order_by('-date')
        region = '부산'
    elif num == 3:
        postlist = postlist.filter(country = '광주').order_by('-date')
        region = '광주'
    elif num == 4:
        postlist = postlist.filter(country = '울산').order_by('-date')
        region = '울산'
    elif num == 5:
        postlist = postlist.filter(country = '대구').order_by('-date')
        region = '대구'
    elif num == 6:
        postlist = postlist.filter(country = '대전').order_by('-date')
        region = '대전'
    elif num == 7:
        postlist = postlist.filter(country = '인천').order_by('-date')
        region = '인천'
    elif num == 8:
        postlist = postlist.filter(country = '경기도').order_by('-date')
        region = '경기도'
    elif num == 9:
        postlist = postlist.filter(country = '강원도').order_by('-date')
        region = '강원도'
    elif num == 10:
        postlist = postlist.filter(country = '충청남도').order_by('-date')
        region = '충청남도'
    elif num == 11:
        postlist = postlist.filter(country = '충청북도').order_by('-date')
        region = '충청북도'
    elif num == 12:
        postlist = postlist.filter(country = '경상북도').order_by('-date')
        region = '경상북도'
    elif num == 13:
        postlist = postlist.filter(country = '전라북도').order_by('-date')
        region = '전라북도'
    elif num == 14:
        postlist = postlist.filter(country = '경상남도').order_by('-date')
        region = '경상남도'
    elif num == 15:
        postlist = postlist.filter(country = '전라남도').order_by('-date')
        region = '전라남도'
    elif num == 16 : #16
        postlist = postlist.filter(country = '제주도').order_by('-date')
        region = '제주도'
    else :
        postlist = postlist.order_by('-date')
        region = '전체'

    context['region'] = region
    context['postlist'] = postlist
    return render(request, 'mainapp/RegionPostList.html', context)

def edit_posting(request):
    return render(request, 'mainapp/edit_posting.html')

web/artproject/mainapp/templates/mainapp/RegionPostList.html
{% extends 'base3.html' %}
{% load static %}

{% block style %}
{% endblock %}
{% block content %}
    <h3>{{region}} 예술 기록</h3>
    {% if postlist %}
    <table border="1">
        <th>no</th>
        <th>날짜</th>
        <th>도시</th>
        <th>장소이름</th>
        {% for post in postlist %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{post.date}}</td>
                <td>{{post.city}}</td>
                <td><a href="/{{post.pk}}">{{post.name}} 클릭</a></td>
            </tr>
        {% endfor %}
    </table>
    {% else %}
        해당지역의 게시글이 없습니다.<br>
    {% endif %}
    {% comment %} <button onclick="javascript:history.back();">뒤로가기</button> {% endcomment %}
    <button onclick="window.close();">창닫기</button>
{% endblock %}

web/artproject/mainapp/templates/mainapp/edit_posting.html
{% extends 'base3.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'mainapp/home.css' %}"> 
{% endblock %}

{% block content %}
    <h3>editpage</h3>
    <button onclick="javascript:history.back();">뒤로가기</button>
    <button onclick="window.close();">창닫기</button>
{% endblock %} 

web/artproject/mainapp/templates/mainapp/home.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'mainapp/home.css' %}" type='text/css'> 
{% endblock %}

{% block content %}
<img id='feature3' src={% static 'mainapp/feature3.png' %} alt='feature3'>
<div id='menu'>
    <a href="{% url 'mainapp:map' %}">
        <div id='menu_box'>
            <h3>마이맵</h3>
            나의 예술 여행 지도 >
        </div>
    </a>
    <a href="{% url 'subapp:search' %}">
        <div id='menu_box'>
            <h3>예술 검색</h3>
            나를 위한 전시, 공연, 행사 정보 검색하기 >
        </div>
    </a>
    <a href="{% url 'secondapp:place_search' %}">
        <div id='menu_box'>
            <h3>공간 검색</h3>
            지역 예술 회관 및 문화 공간 검색하기 >
        </div>
    </a>
</div>
<img id='feature' src={% static 'mainapp/feature2.png' %} alt='feature'>
{% endblock %}

web/artproject/mainapp/templates/mainapp/posting.html
{% extends 'base3.html' %}
{% load static %}

{% block style %}
    {% comment %} <link rel="stylesheet" href="{% static 'mainapp/home.css' %}">  {% endcomment %}
{% endblock %}

{% block content %}
    {% comment %} <h1>게시글 개별 페이지</h1> {% endcomment %}
    <h3>장소명:{{post.name}}</h3>
    <div id='text_contents'>
        <p>항목:{{post.item}}</p>
        <p>방문날짜:{{post.date}}</p>
        <p>위치:{{post.country}}/{{post.city}}</p>
        <p>공개여부:{{post.public}}</p>
        <p>평점:{{post.rating}}</p>
        {% if post.image %}
            <img src = "{{ post.image.url }}" alt="{{post.name}}" width="95%">
            <br>
        {% endif %}
        <p>후기:{{post.comment}}</p>
    </div>
    <div id='container'>
        <button id='ct_items' onclick="javascript:history.back();">뒤로가기</button>
        <button id='ct_items' onclick="window.close();">창닫기</button>
        <a id='ct_items' href="{% url 'mainapp:edit_posting' %}">수정</a>
        <a id='ct_items' href="/{{post.pk}}/remove">삭제</a>
    </div>
{% endblock %}

web/artproject/mainapp/templates/mainapp/remove_post.html
{% extends 'base3.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'mainapp/home.css' %}"> 
{% endblock %}

{% block content %}
    <form action="{% url 'mainapp:remove_post' Post.pk %}" method="POST">
        {% csrf_token %}
        <div id='text_contents'>
            <h3>정말 삭제하시겠습니까?</h3>
            <h3>{{ Post.name }}</h3>
            <p>항목:{{Post.item}}</p>
            <p>방문날짜:{{Post.date}}</p>
            <p>위치:{{Post.country}}/{{Post.city}}</p>
            <p>공개여부:{{Post.public}}</p>
            <p>평점:{{Post.rating}}</p>
            <p>후기:{{Post.comment}}</p>
            {% if Post.image %}
                <img src = "{{Post.image.url}}" alt="{{Post.name}}" width="95%"><br>
            {% endif %}
        </div>
        <div id='container'>
            <button id='ct_items'>삭제</button>
            <a id='ct_items' href="{% url 'mainapp:map' %}">목록</a>
        </div>
    </form>
{% endblock %}

web/artproject/mainapp/templates/mainapp/upload.html
{% extends 'base2.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'mainapp/upload.css' %}" type='text/css'> 
{% endblock %}

{% block content %}
<br>
<a id='back' href="{% url 'mainapp:map' %}">&lt; BACK</a>
<h3>마이맵 업로드</h3>
<table>
    <div id='container'>
        <form action="{% url 'mainapp:upload' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div id='container_sub'>
                장소명
                <input type="text" name="name"><br>
            </div>
            <div id='container_sub'>
                <div>
                    후기<br>
                    <textarea rows="10" cols="40" name="comment"></textarea><br>
                </div>
            </div>
            <div id='container_sub'>
                이미지
                <input type="file" name="image"><br>
            </div>
            <div id='container_sub'>
                평점(5.0/
                <input type="number" name="rating">)<br>
            </div>
            <div id='container_sub'>
                방문일
                <input type="date" name="date"><br>
            </div>
            <div id='container_sub'>
                <!-- 항목
                <select name="item">
                    <option value="전시회">전시회</option>
                    <option value="박람회">박람회</option>
                    <option value="공연">공연</option>
                </select><br> -->
            </div>
            <div id='container_sub'>
                지역
                <select name="country">
                    <option value="서울">서울</option>
                    <option value="부산">부산</option>
                    <option value="대구">대구</option>
                    <option value="인천">인천</option>
                    <option value="광주">광주</option>
                    <option value="대전">대전</option>
                    <option value="울산">울산</option>
                    <option value="세종시">세종시</option>
                    <option value="경기도">경기도</option>
                    <option value="강원도">강원도</option>
                    <option value="충청북도">충청북도</option>
                    <option value="충청남도">충청남도</option>
                    <option value="전라북도">전라북도</option>
                    <option value="전라남도">전라남도</option>
                    <option value="경상북도">경상북도</option>
                    <option value="경상남도">경상남도</option>
                    <option value="제주도">제주도</option>
                </select><br>
            </div>
            <div id='container_sub'>
                도시
                <input type="text" name="city">
            </div>
            <br>
            <input id='upload_bt' type="submit" value="글쓰기">
        </div>
    </form>
</table>

{% endblock %}