web/artproject/accountapp/urls.py
from django.urls import path
from . import views

app_name = 'accountapp'
urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('info/', views.information, name = 'information'),
    path('info_detail',views.info_detail, name = 'info_detail'),
]

web/artproject/artproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accountapp/', include('accountapp.urls')),
    path('subapp/', include('subapp.urls')),
    path('secondapp/', include('secondapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #url/media/파일명 점근을 가능하게 한다.

web/artproject/mainapp/urls.py
from django.urls import path 
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = 'mainapp'
urlpatterns = [
    path('', views.home, name='home'), 
    path('map/', views.map, name='map'), #postlist보여줌
    path('<int:pk>/',views.posting, name="posting"), #post 세부내용
    path('upload/', views.upload, name='upload'), #postupload 
    path('<int:pk>/remove/', views.remove_post, name='remove_post'),
    path('map/<int:num>/', views.RegionPostList, name='RegionPostList'),
    path('edit_posting', views.edit_posting, name='edit_posting'),
]

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/artproject/secondapp/urls.py
from django.urls import path 
from . import views

app_name = 'secondapp'
urlpatterns = [
    path("place_search/", views.place_search, name="place_search"),
    path('place_deatil/<int:pk>', views.place_detail, name="place_detail"),
]

web/artproject/subapp/urls.py
from django.urls import path 
from . import views

app_name = 'subapp'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('detail/<int:content_pk>', views.detail, name='detail'),
]

web/artproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ART Hackathon</title>
    <link rel="stylesheet" href="{% static 'base.css' %}" type="text/css">
    {% block style %}
    {% endblock %}
</head>
<body>
    <div id='nav'>
        <a href="{% url 'mainapp:home' %}"><img id='logo' src={% static 'logo.png' %} alt='logo'></a>
        {% if user.is_authenticated %}
        <!-- 로그인 한 사용자 -->
            <li><a href="{% url 'mainapp:map' %}">마이맵</a></li>
            <li><a href="{% url 'subapp:search' %}">예술검색</a></li>
            <li><a href="{% url 'secondapp:place_search' %}">공간검색</a></li>
            <li>
                <form action="{% url 'accountapp:logout' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="path" value="{{request.path}}">
                    <button id='log_out'type = submit>로그아웃</button>
                </form>
            </li>
        {% else %}
            <!-- 로그인하지 않은 사용자 -->
            <!-- <li><a href="{% url 'accountapp:login' %}">Log-In</a></li> -->
            <li><a href="{% url 'mainapp:map' %}">마이맵</a></li>
            <li><a href="{% url 'subapp:search' %}">예술검색</a></li>
            <li><a href="{% url 'secondapp:place_search' %}">공간검색</a></li>
            <li><a href="{% url 'accountapp:login' %}?next={{ request.path }}">로그인</a></li>
        {% endif %}
    </div>

    {% block content %}
    {% endblock %}
    <div id='bottom'>
        <img id='text_logo' src={% static 'logo2.png' %} alt='logo'><br>
        project team aloha 김신영 이지원 주하영 천희국 최다인<br>
        copyrightⓒ 2020 All rights reserved by aloha
    </div>    
</body>
</html>

web/artproject/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ART Hackathon</title>
    <link rel="stylesheet" href="{% static 'base2.css' %}" type="text/css">
    {% block style %}
    {% endblock %}
</head>
<body>
    <div id='nav'>
        <a href="{% url 'mainapp:home' %}"><img id='logo' src={% static 'white_logo.png' %} alt='logo'></a>
        {% if user.is_authenticated %}
        <!-- 로그인 한 사용자 -->
            <li><a href="{% url 'mainapp:map' %}">마이맵</a></li>
            <li><a href="{% url 'subapp:search' %}">예술검색</a></li>
            <li><a href="{% url 'secondapp:place_search' %}">공간검색</a></li>
            <li>
                <form action="{% url 'accountapp:logout' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="path" value="{{request.path}}">
                    <button id='log_out'type = submit>로그아웃</button>
                </form>
            </li>
        {% else %}
            <!-- 로그인하지 않은 사용자 -->
            <!-- <li><a href="{% url 'accountapp:login' %}">Log-In</a></li> -->
            <li><a href="{% url 'mainapp:map' %}">마이맵</a></li>
            <li><a href="{% url 'subapp:search' %}">예술검색</a></li>
            <li><a href="{% url 'secondapp:place_search' %}">공간검색</a></li>
            <li><a href="{% url 'accountapp:login' %}">로그인</a></li>
        {% endif %}
    </div>

    {% block content %}
    {% endblock %}
    <div id='bottom'>
        <img id='text_logo' src={% static 'logo2.png' %} alt='logo'><br>
        project team aloha 김신영 이지원 주하영 천희국 최다인<br>
        copyrightⓒ 2020 All rights reserved by aloha
    </div>  
</body>
</html>

web/artproject/templates/base3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ART Hackathon</title>
    <link rel="stylesheet" href="{% static 'base3.css' %}" type="text/css">
    {% block style %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
    {% comment %} <div id='bottom'>
        <img id='text_logo' src={% static 'logo2.png' %} alt='logo'><br>
        project team aloha 김신영 이지원 주하영 천희국 최다인<br>
        copyrightⓒ 2020 All rights reserved by aloha
    </div>     {% endcomment %}
</body>
</html>