web/artproject/accountapp/urls.py
from django.urls import path
from . import views

app_name = 'accountapp'
urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('info/', views.information, name = 'information'),
    path('info_detail',views.info_detail, name = 'info_detail'),
]

web/artproject/artproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accountapp/', include('accountapp.urls')),
    path('subapp/', include('subapp.urls')),
    path('secondapp/', include('secondapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #url/media/파일명 점근을 가능하게 한다.

web/artproject/subapp/urls.py
from django.urls import path 
from . import views

app_name = 'subapp'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('detail/<int:content_pk>', views.detail, name='detail'),
]

web/artproject/accountapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class info(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True)
    age=models.IntegerField()
    region=models.CharField(max_length=30)
    gender=models.CharField(max_length=30)

web/artproject/accountapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from .models import info

# Create your views here.

def sign_up(request):
    context={}
    # POST Method
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        password_check = request.POST['password_check']

        # 제대로 입력되었을 경우
        if (username and password and password_check == password):
            new_user = User.objects.create_user(
                username = username,
                password = password,
            )
            # 로그인후 home을 redirect
            auth.login(request, new_user)
            return redirect('accountapp:information')
        else:
            context['error'] = "아이디와 비밀번호를 다시 확인해주세요."

    # GET Method
    return render(request, 'accountapp/signup.html', context)

def information(request):
    if request.method == 'POST':
        new_info=info.objects.create(
            user=User.objects.get(username = request.user.get_username()),
            age = request.POST['age'],
            region=request.POST['region'],
            gender=request.POST['gender'],
        )
        return redirect('mainapp:home')
    return render(request, 'accountapp/info.html')

def info_detail(request):
    detail=info.objects.all()
    return render(request, 'accountapp/info_detail.html',{'detail':detail})

def login(request):
    context={}

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        if username and password:
            user = auth.authenticate(
                request,
                username = username,
                password = password
            )
            if user is not None:
                # 사용자가 있으면 로그인후 home으로
                auth.login(request, user)
                next_url = request.POST.get('next')
                if next_url :
                    return redirect(next_url)
                return redirect('mainapp:home')
            else:
                context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'
        else:
            #아이디나 비밀번호가 제대로 입력되지 않았을때
            context['error'] = '아이디와 비밀번호를 모두 입력해주세요.'

    # Get Method
    next_url = request.GET.get('next')
    context['next'] = next_url
    return render(request, 'accountapp/login.html', context)

def logout(request):
    if request.method == "POST":
        auth.logout(request)
    # 로그아웃하면 홈으로
    # return redirect("mainapp:home")
    # 로그아웃하면 이전 페이지로
    return redirect(request.POST['path'])

web/artproject/accountapp/templates/accountapp/info.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accountapp/login.css' %}" type="text/css"> 
{% endblock %}

{% block content %}
{% comment %} <h1>info</h1> {% endcomment %}

<h3>{{user.username}}님 환영합니다</h3>
<div id='intro'>
    맞춤형 예술 공간 추천을 위한 정보입력 페이지 입니다.
</div>
<div id='login_box'>
    <form action="{% url 'accountapp:information'%}" method="POST">
        {% csrf_token %}
        <div id='question'>
            나이를 입력해주세요
        </div>
        <input type="number" name="age"><br>
        <div id='question'>
            거주 지역을 선택해주세요
        </div>
        <select name="region">
            <option value="서울">서울</option>
            <option value="부산">부산</option>
            <option value="대구">대구</option>
            <option value="인천">인천</option>
            <option value="광주">광주</option>
            <option value="대전">대전</option>
            <option value="울산">울산</option>
            <option value="세종시">세종시</option>
            <option value="경기도">경기도</option>
            <option value="강원도">강원도</option>
            <option value="충청북도">충청북도</option>
            <option value="충청남도">충청남도</option>
            <option value="전라남도">전라남도</option>
            <option value="경상북도">경상북도</option>
            <option value="경상남도">경상남도</option>
            <option value="제주도">제주도</option>
        </select><br>
        <div id='question'>
            성별을 선택해주세요
        </div>
        <select name="gender">
            <option value="남성">남성</option>
            <option value="여성">여성</option>
        </select>
        <br>
        <br>
        <input type="submit" value="확인">
    </form>
</div>
{% endblock %} 

web/artproject/accountapp/templates/accountapp/info_detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accountapp/login.css' %}" type="text/css"> 
{% endblock %}

{% block content %}
<h1>info_detail</h1>
{{detail.user}}
{{detail.region}}

{% endblock %} 

web/artproject/accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accountapp/login.css' %}" type="text/css"> 
{% endblock %}

{% block content %}
    {% if error %}
    <div>
        {{ error }}
    </div>
    {% endif %}
    <br>
    <br>
    <br>
    <div id='login_box'>
        <form action="{% url 'accountapp:login' %}" method="POST">
            {% csrf_token %}
            <h3>LOGIN</h3>
            <div>
                {% comment %} <label class='log_lb' for="username">아이디</label> {% endcomment %}
                <input type="text" id = 'username' placeholder="아이디" name="username">
            </div>
            <div >
                {% comment %} <label class='log_lb' for="password">비밀번호</label> {% endcomment %}
                <input type="password" id='password' placeholder="비밀번호" name="password">
            </div>
            <input type="hidden" name="next" value="{{ next }}">
            <button type="submit">로그인</button>
        </form>
        <div class="account">
            Don't have account?
            <a href="{% url 'accountapp:sign_up' %}">Signup Now</a>
        </div>
    </div>
{% endblock %}

web/artproject/accountapp/templates/accountapp/signup.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accountapp/login.css' %}" type="text/css"> 
{% endblock %}

{% block content %}
    {% if error %}
    <div>
        {{ error }}
    </div>
    {% endif %}
    <br>
    <br>
    <br>
    <div id='login_box'>
        <form action="{% url 'accountapp:sign_up' %}" method="POST">
            {% csrf_token %}
            <h3>SIGNUP</h3>
            <div>
                {% comment %} <label class='log_lb' for="username">아이디</label> {% endcomment %}
                <input type="text" id = 'username' placeholder="아이디" name="username">
            </div>
            <div >
                {% comment %} <label class='log_lb' for="password">비밀번호</label> {% endcomment %}
                <input type="password" id='password' placeholder="비밀번호" name="password">
            </div>
            <div >
                {% comment %} <label class='log_lb' for="password_check">비밀번호 확인</label> {% endcomment %}
                <input type="password" id='password_check' placeholder="비밀번호 확인" name="password_check">
            </div>
            <button type="submit">회원가입</button>
        </form>
        <div class="account">
            Already have account?
            <a href="{% url 'accountapp:login' %}">Login Now</a>
        </div>
    </div>
{% endblock %}