web/artproject/artproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accountapp/', include('accountapp.urls')),
    path('subapp/', include('subapp.urls')),
    path('secondapp/', include('secondapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #url/media/파일명 점근을 가능하게 한다.

web/artproject/subapp/urls.py
from django.urls import path 
from . import views

app_name = 'subapp'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('detail/<int:content_pk>', views.detail, name='detail'),
]

web/artproject/subapp/models.py
from django.db import models

# Create your models here.

class ArtInfoDB(models.Model):
    title = models.CharField(max_length=30)
    host = models.CharField(max_length=30)
    region = models.CharField(max_length=10, null=True)
    category = models.CharField(max_length=10)
    start_date = models.DateField(null=True, auto_now=False, auto_now_add=False)
    end_date = models.DateField(null=True, auto_now=False, auto_now_add=False)

    def __str__(self):
        return f'{self.id}: {self.title} - {self.category}'

class PerformanceDB(models.Model):
    artinfo = models.ForeignKey(
        ArtInfoDB, on_delete=models.CASCADE, related_name='performance')
    cl = models.CharField(max_length=10) #소분류
    genre = models.CharField(max_length=10)
    place = models.CharField(max_length=30)
    Vrate = models.CharField(max_length=50, null=True) #관람등급 view rate

class FestivalDB(models.Model):
    artinfo = models.ForeignKey(
        ArtInfoDB, on_delete=models.CASCADE, related_name='festival')
    content = models.TextField() #상세내용

web/artproject/subapp/views.py
from django.shortcuts import render
from .models import ArtInfoDB, PerformanceDB, FestivalDB
from django.db.models import Q, Count
# Create your views here.

def search(request):
    context={}
    start = None
    end = None
    category = None

    contents = ArtInfoDB.objects.all()
    # 키워드 검색
    kw = request.GET.get('kw', '')
    context['kw'] = kw
    if kw !='': #키워드 입력이 들어왔을때
        contents = contents.filter(
            Q(title__contains=kw) | Q(host__contains=kw)|
            Q(region__contains=kw) | Q(category__contains=kw)
        ).distinct()
    else :
        pass

    # 시간 필터링
    # start = request.GET.get('start', '')
    # end = request.GET.get('end', '')
    # context['start'] = start
    # context['end'] = end
    
    category = request.GET.get('category', 'all')
    context['category'] = category

    if category == 'festival' : 
        contents = contents.filter(category = '축제/행사')
    elif category == 'performance':
         contents = contents.filter(category = '공연/전시')
    else : 
        pass
        
    context['contents'] = contents
    return render(request, 'subapp/search.html', context)

def detail(request, content_pk):
    context={}
    Aitem = None
    Bitem = None
    contentt = ArtInfoDB.objects.get(pk = content_pk)

    if contentt.category == '공연/전시' : 
        Aitem = PerformanceDB.objects.get(artinfo_id=content_pk)
    elif contentt.category == '축제/행사':
        Bitem = FestivalDB.objects.get(artinfo_id=content_pk)
    else : #'미술작품/건축물'
        item = ArtWorkDB.objects.get(artinfo_id=content_pk)

    context['Aitem'] = Aitem
    context['Bitem'] = Bitem
    return render(request, 'subapp/detail.html', context)

web/artproject/subapp/templates/subapp/detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'subapp/detail.css' %}" type='text/css'> 
{% endblock %}
{% block content %}
    {% comment %} <img id='feature3' src={% static 'mainapp/feature3.png' %} alt='feature3'> {% endcomment %}
    <div id='contents'>
        {% if Aitem  %}
        <div id='place'>
            <h4> {{ Aitem.artinfo.title }} </h4>
        </div>
        <div id='container1'>
            <div id='container2'>
                주 최<br>
                기 간<br>
                분 류<br>
                장 르<br>
                장 소<br>
                관람등급<br>
            </div>
            <div id='container3'>
                {{ Aitem.artinfo.host }} <br>
                {{ Aitem.artinfo.start_date }} ~ {{ Aitem.artinfo.end_date }} <br>
                {{Aitem.artinfo.category}} / {{ Aitem.cl }} <br>
                {{ Aitem.genre }} <br>
                {{Aitem.artinfo.region}}/{{ Aitem.place }} <br>
                {{Aitem.Vrate}} <br>
            </div>
        </div>
        {% endif %}

        {% if Bitem %}
        <h1> {{ Bitem.artinfo.title }} </h1>
        <div id='container1'>
            <div id='container2'>
                주최<br>
                기간<br>
                분류<br>
                지역<br>
                내용<br>
            </div>
            <div id='container3'>
                {{ Bitem.artinfo.host}} <br>
                {{Bitem.artinfo.start_date}} ~ {{Bitem.artinfo.end_date}} <br>
                {{Bitem.artinfo.category}} <br>
                {{Bitem.artinfo.region}} <br>
                {{Bitem.content}} <br>
            </div>
        </div>
        {% endif%}
    </div>
{% endblock %}

web/artproject/subapp/templates/subapp/search.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'subapp/result.css' %}" type="text/css">
{% endblock %}

{% block content %}
<img id='feature3' src={% static 'mainapp/feature3.png' %} alt='feature3'>
<h3>WAPLE 예술검색</h3>
    <div id='intro'>
        waple 예술검색은 전국의 다양한 전시, 공연, 행사 등을, 지역, 성별, 연령별 선호도 기준으로 검색할 수 있습니다.
    </div>
 <!-- 다시검색 -->
 <div>
    <form action="{% url 'subapp:search' %}" method="GET">
        {% csrf_token %}
        <div id='sb_ct'>
            <input id='search_box' type="text" {%if kw == '' %}placeholder="wowplace"{%else%}placeholder={{kw}}{%endif%} name="kw" value="{{kw|default_if_none:''}}">
            <button id='bt' type="submit" >검색</button> <br>
        </div>
        <div id='tag'>
            <!-- <span>#경주</span>
            <span>#경주 공연</span>
            <span>#서울 전시회</span> -->
        </div>
    <!-- 필터링 -->
        <h3>WAPLE 필터</h3>
        <br>
        <br>
        <div id='filter_ct'>
            <button id='fixed1' type="reset">초기화</button>
            <div id='sub_title'>
                날짜
            </div>            
            <div id='sb_ct'>
                <input type="date" name="start"> ~ <input type="date" name="end" > <br>
            </div>
            <div id='sub_title'>
                정렬순
                <p>업데이트 예정</p>
            </div>
            <div id='sub_title'>
                유형
            </div>
            <div>
                <div id='radio_ct'>
                    <input type="radio" name="category" value="all"id="all" {% if category == 'all' %}checked{% endif %} >
                    <label for="all">전체</label>
                    <input type="radio" name="category" value="performance"id="performance" {% if category == 'performance' %}checked{% endif %}>
                    <label for="performance">공연/전시</label>
                    <input type="radio" name="category" value="festival"id="festival" {% if category == 'festival' %}checked{% endif %}>
                    <label for="festival">축제/행사</label><br>
                </div>
            </div>
            <button id='fixed2' type="submit">적용</button>
        </div>
    </form>
 </div>
 <!-- 결과 -->
 <div>
     <h3>WAPLE 검색 결과</h3>
     {% for content in contents %}
    <div id='place'>
        <h4><a href="{% url 'subapp:detail' content.pk %}">{{content.title}}</a></h4>
        <b>주최 / 작가</b> : {{content.host}} <br>
        {% if content.region != N %} <b>지역</b> : {{content.region}}<br> {% endif %}
        <b>분류</b>: {{content.category}}
    </div>
    {% empty %}
    <div>
        0 result found.
    </div>
    {% endfor %}
 </div>
{% endblock %}